// The Swift models against the agent's own serialisation.
//
// `desktop/control/tests/fixtures/control-protocol.json` is generated by the
// Rust test suite from the real `pliwee-control` types. Every response and
// event in it must decode here, and every request this app can send must
// encode to exactly the JSON the Rust types produce.

import Foundation
import Testing
@testable import PliweeKit

enum Fixture {
    static let url: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // PliweeKitTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // macos
        .deletingLastPathComponent() // repository root
        .appendingPathComponent("desktop/control/tests/fixtures/control-protocol.json")

    static func load() throws -> [String: Any] {
        let data = try Data(contentsOf: url)
        return try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    static func section(_ name: String) throws -> [String: Any] {
        try #require(try load()[name] as? [String: Any], "fixture has no \(name)")
    }

    static func data(_ section: String, _ key: String) throws -> Data {
        let object = try #require(try Self.section(section)[key], "fixture has no \(section).\(key)")
        return try JSONSerialization.data(withJSONObject: object)
    }
}

@Suite struct ControlProtocolTests {
    /// Every request this app can send, named as the fixture names it.
    static let requests: [(String, Request)] = {
        let fp = "a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90"
        return [
            ("status", .status),
            ("devices", .devices),
            ("pair", .pair(ttlSecs: 120)),
            ("pair_default_ttl", .pair(ttlSecs: nil)),
            ("confirm", .confirm(accept: true)),
            ("unpair", .unpair(device: fp)),
            ("hide_revoked_device", .hideRevokedDevice(fingerprint: String(repeating: "ff", count: 32))),
            ("hide_all_revoked_devices", .hideAllRevokedDevices),
            ("ping", .ping(device: fp)),
            ("grant", .grant(device: fp, capability: "files.v1", granted: true)),
            ("send", .send(device: fp, path: "/Users/ana/Desktop/report.pdf")),
            ("transfers", .transfers),
            ("watch_file_offers", .watchFileOffers),
            ("file_decision", .fileDecision(transfer: "00112233445566778899aabbccddeeff", accept: false)),
            ("cancel_transfer", .cancelTransfer(transfer: "00112233")),
            ("clipboard_status", .clipboardStatus),
            ("clipboard_send", .clipboardSend(device: fp, sensitive: false)),
            ("clipboard_apply", .clipboardApply(device: fp)),
            ("clipboard_policy", .clipboardPolicy(device: fp, flag: .autoReceive, enabled: true)),
            ("notifications_status", .notificationsStatus),
            ("notifications_policy", .notificationsPolicy(device: fp, setting: .mirror(enabled: true))),
            ("notifications_policy_when_locked", .notificationsPolicy(device: fp, setting: .whenLocked(policy: "app-only"))),
        ]
    }()

    @Test func theFixtureIsTheOneTheRustSuiteGenerates() throws {
        let comment = try #require(try Fixture.load()["$comment"] as? [String])
        #expect(comment.joined().contains("control_fixtures.rs"))
    }

    @Test func everyRequestEncodesToExactlyTheAgentsJson() throws {
        let fixture = try Fixture.section("requests")
        for (name, request) in Self.requests {
            let expected = try #require(fixture[name] as? NSDictionary, "fixture has no request \(name)")
            var line = try request.line()
            #expect(line.last == 0x0A, "a request is one line")
            line.removeLast()
            #expect(!line.contains(0x0A), "\(name) must not contain a newline")
            let encoded = try #require(try JSONSerialization.jsonObject(with: line) as? NSDictionary)
            #expect(encoded == expected, "\(name): \(encoded) != \(expected)")
        }
    }

    @Test func everyRequestInTheFixtureIsOneThisAppCanSend() throws {
        let names = Set(try Fixture.section("requests").keys)
        #expect(names == Set(Self.requests.map(\.0)), "a request kind is missing on one side")
    }

    @Test func everyResponseDecodes() throws {
        let names = try Fixture.section("responses").keys.sorted()
        #expect(names.count == 8)
        for name in names {
            let data = try Fixture.data("responses", name)
            #expect(throws: Never.self, "response \(name)") {
                _ = try ControlCoding.response(from: data)
            }
        }
    }

    @Test func theStatusReportDecodesFieldByField() throws {
        let response = try ControlCoding.response(from: try Fixture.data("responses", "status"))
        guard case let .status(status) = response else {
            Issue.record("expected status, got \(response)"); return
        }
        #expect(status.deviceName == "Ana's MacBook Air")
        #expect(status.keyBacking == "software")
        #expect(status.listenPort == 55432)
        #expect(status.capabilities.contains("clipboard.v1"))
        #expect(status.connections.first?.negotiatedCapabilities == ["battery.v1", "files.v1"])
        #expect(status.connections.first?.state == .connected)
        #expect(status.devices.count == 2)
        #expect(status.devices[0].battery?.percentage == 81)
        #expect(status.devices[1].state == .revoked)
        #expect(status.devices[1].battery == nil, "an offline device never carries a battery")
        #expect(status.migratedFrom == nil)
    }

    @Test func singleShotRepliesDecodeToTheirCases() throws {
        #expect(try ControlCoding.response(from: Fixture.data("responses", "pong")) == .pong(rttMs: 18))
        #expect(try ControlCoding.response(from: Fixture.data("responses", "ok")) == .ok(message: "granted files.v1"))
        #expect(try ControlCoding.response(from: Fixture.data("responses", "error")) == .error(message: "no such device"))
        guard case let .transfers(transfers) = try ControlCoding.response(from: Fixture.data("responses", "transfers")) else {
            Issue.record("expected transfers"); return
        }
        #expect(transfers.map(\.seq) == [4, 5])
        #expect(transfers[0].storedAt == "/Users/ana/Downloads/Pliwee/holiday photo.jpg")
        #expect(transfers[1].percentage == nil, "a zero-byte file has no percentage")
        #expect(transfers[1].failureCode == "declined_by_user")
        guard case let .clipboard(clip) = try ControlCoding.response(from: Fixture.data("responses", "clipboard")) else {
            Issue.record("expected clipboard"); return
        }
        #expect(clip.watchAvailable == false)
        #expect(clip.pending.first?.sensitive == true)
    }

    @Test func everyEventDecodesToAKnownCase() throws {
        let names = try Fixture.section("events").keys.sorted()
        #expect(names.count == 7)
        for name in names {
            let message = try ControlCoding.streamMessage(from: try Fixture.data("events", name))
            guard case let .event(event) = message else {
                Issue.record("\(name) did not decode as an event"); continue
            }
            if case .unknown = event { Issue.record("\(name) decoded as unknown") }
        }
    }

    @Test func eventsCarryTheirFields() throws {
        func event(_ name: String) throws -> Event {
            guard case let .event(e) = try ControlCoding.streamMessage(from: try Fixture.data("events", name)) else {
                throw ControlError.malformed(name)
            }
            return e
        }
        #expect(try event("pairing_ready") == .pairingReady(payload: "pliwee://pair?v=1&fp=0f0f", qrAscii: "██", expiresInSecs: 120))
        #expect(try event("finished") == .finished(status: "paired", detail: "A1B2 C3D4 E5F6 0718"))
        #expect(try event("file_approval_ready") == .fileApprovalReady(unattended: false))
        guard case let .fileOfferRequest(offer) = try event("file_offer_request") else {
            Issue.record("expected an offer"); return
        }
        #expect(offer.transferId == "00112233445566778899aabbccddeeff")
        #expect(offer.sizeBytes == 300_000)
        guard case let .transferProgress(progress) = try event("transfer_progress") else {
            Issue.record("expected progress"); return
        }
        #expect(progress.state == TransferState.completed)
    }

    @Test func aStreamMayBeAnsweredWithAPlainError() throws {
        let line = Data(#"{"error":{"message":"could not start pairing: busy"}}"#.utf8)
        #expect(try ControlCoding.streamMessage(from: line) == .response(.error(message: "could not start pairing: busy")))
    }

    @Test func anEventFromANewerAgentIsUnknownRatherThanAnError() throws {
        let line = Data(#"{"event":"something_new","x":1}"#.utf8)
        #expect(try ControlCoding.streamMessage(from: line) == .event(.unknown("something_new")))
    }

    @Test func aDeviceStateFromANewerAgentIsUnknown() throws {
        let line = Data(#""quarantined""#.utf8)
        #expect(try JSONDecoder().decode(DeviceState.self, from: line) == .unknown)
    }

    @Test func fieldsTheAgentDefaultsMayBeAbsent() throws {
        // `#[serde(default)]` on the Rust side: an older agent omits them.
        let line = Data(#"""
        {"transfer_id":"aa","device_name":"d","fingerprint_short":"f","direction":"sending",
         "filename":"x","mime_type":"m","size_bytes":1,"bytes_transferred":0,"percentage":null,
         "state":"offered","failure":null,"stored_at":null}
        """#.utf8)
        let t = try ControlCoding.decoder().decode(TransferReport.self, from: line)
        #expect(t.seq == 0)
        #expect(t.failureCode == nil)
    }
}
